Repository OpenDRR/opendrr-api, pull requests merged in 2021-04, with the labels that each got.

#79 update ES mappings for building level aggregation
  python/dsra_postgres2es.py
  python/exposure_postgres2es.py
  python/hazardThreat_postgres2es.py
  python/psra_postgres2es.py
  python/riskDynamics_postgres2es.py
  python/socialFabric_postgres2es.py
Labels: Bug, Kibana, Priority: Should Have, Severity: Major, Task

#82 add_data.sh: Add --retry option to curl download
  python/add_data.sh
Labels: Enhancement

#86 Update sovi hazthreat feb2021
  python/add_data.sh
Labels: Enhancement, Priority: Must Have, Severity: Major, Task
