Repository OpenDRR/opendrr-api, pull requests merged in 2021-06, with the labels that each got.

#106 add_data: Fix github_token parsing from config.ini
  python/add_data.sh
Labels: Bug

#118 docker-compose: Fix named volume "pg-data" in db-opendrr
  docker-compose.yml
Labels: Severity: Normal

#124 Fix "./add_data.sh not found" error on Windows
  .gitattributes
  python/Dockerfile
  python/add_data.sh
Labels: Bug, Priority: Should Have, Task

#123 Update source to openquake inputs
  python/add_data.sh
Labels: Enhancement, Priority: Must Have, Severity: Normal, Task

#125 add_data: Allow get_git_lfs_pointers_of_csv_file to be re-run
  python/add_data.sh
Labels: Bug, Severity: Normal
