Repository OpenDRR/opendrr-api, pull requests merged in 2022-01, with the labels that each got.

#156 pull model-factory release instead of cloning
  python/add_data.sh
Labels: Enhancement

#158 filter out MMI shakemap files
  python/add_data.sh
Labels: Bug

#162 Update social fabric jan2022
  python/add_data.sh
Labels: Enhancement, Task
